"""remove chatbot phase 

Revision ID: 321a39281572
Revises: 4e933e2c6680
Create Date: 2025-03-21 16:00:21.837215

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '321a39281572'
down_revision = '4e933e2c6680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot')
    op.add_column('meeting', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Add owner_id as nullable first
    op.add_column('meeting', sa.Column('owner_id', sa.Uuid(), nullable=True))
    
    # Get a user ID to assign to existing meetings
    # Option 1: Get the first user from the database
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM \"user\" LIMIT 1"))
    user_id = result.scalar()
    
    if user_id:
        # Update existing records with the user ID
        op.execute(sa.text(f"UPDATE meeting SET owner_id = '{user_id}'"))
    else:
        # If no users exist, you might want to delete existing meetings
        # or create a default user
        op.execute(sa.text("DELETE FROM meeting"))
    
    # Now make the column non-nullable
    op.alter_column('meeting', 'owner_id', nullable=False)
    
    # Continue with the rest of the migration
    op.add_column('meeting', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('meeting', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.alter_column('meeting', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'meeting', 'user', ['owner_id'], ['id'])
    op.add_column('recording', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recording', sa.Column('transcript_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('recording', 'video_url')
    op.drop_column('recording', 'audio_url')
    op.add_column('summary', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('summary', 'summary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('summary', 'content')
    op.add_column('recording', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recording', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('recording', 'transcript_url')
    op.drop_column('recording', 'file_url')
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.alter_column('meeting', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('meeting', 'updated_at')
    op.drop_column('meeting', 'created_at')
    op.drop_column('meeting', 'owner_id')
    op.drop_column('meeting', 'description')
    op.create_table('chatbot',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('logo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('script', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='chatbot_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chatbot_pkey')
    )
    # ### end Alembic commands ###
