"""Fix relationship between Recording and Transcript

Revision ID: e629cb4fced8
Revises: 321a39281572
Create Date: 2025-03-23 14:45:59.036740

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e629cb4fced8'
down_revision = '321a39281572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
